### ISSUE TITLE
main table empty in v1.1.0 - multiple bug reports

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#134]
After the upgrade to 1.1.0 some users reported that their data is gone. One report states that the main table is empty, but when tapped on, it opens the details view and the data is still there, but still not displayed in the main table.

![main](https://user-images.githubusercontent.com/1932462/106523331-3d12e600-64e1-11eb-8fe4-5392de51d2c0.jpg)

![details](https://user-images.githubusercontent.com/1932462/106523313-37b59b80-64e1-11eb-8209-4d1bd1a504e5.jpg)

There are some irregularities in the logs that were mailed to me:

- WeekStateCalculator.loadWeek - Exception: Attempt to invoke virtual method 'org.threeten.bp.LocalDate org.zephyrsoft.trackworktime.model.FlexiReset.getNextResetDate(org.threeten.bp.LocalDate)' on a null object reference
- org.supercsv.exception.SuperCsvReflectionException: unable to find getter for field time in class org.zephyrsoft.trackworktime.model.Event - check that the corresponding nameMapping element matches the field name in the bean
- WorkTimeTrackerApplication.onCreate - WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

Details available per email when confidentiality is assured - please send me an email so I know your address. My email address can be found [here](https://github.com/mathisdt/trackworktime/blob/master/app/src/main/res/values/strings.xml#L8) or [here](https://zephyrsoft.org/contact-about-me).

**Comment by mathisdt** [comment]
@dliw If you have time, could you please have a look at this? The users seem very displeased...

**Comment by dliw** [comment]
That is very unfortunate to hear. In the worst case: the original data is still there. The migration does *not* delete the old event table. If there are too many problems, it would be possible to implement a downgrade to the old version.

I'll send you an email. Without context, these errors are unlikely to be found.

**Comment by dliw** [comment]
>   WorkTimeTrackerApplication.onCreate - WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

This wasn't implemented by me. I only changed the call to ``enqueueUniquePeriodicWork`` because I had hundreds of backup jobs running after one day. Compare
https://github.com/mathisdt/trackworktime/commit/7fd71150b1c736b7af5e610ffd7589ef047b22d8#diff-7d3665c0137bedeae13a99a61126fc73d0a11058cd1d43a0f0049bd0d26f8929R107
with
https://github.com/mathisdt/trackworktime/blob/master/app/src/main/java/org/zephyrsoft/trackworktime/WorkTimeTrackerApplication.java#L109

Also I had exactly this crash. That is why I added the try - catch and the log but forgot about it. I don't know, what is wrong with the work manager.

**Comment by mathisdt** [comment]
Addressed by #135

**Comment by mathisdt** [comment]
I have feedback from an affected user: "It worked. Thank you!"

I don't know if "it" was the updated APK (which didn't make it yet through Google's review process but can be installed from [here](https://github.com/mathisdt/trackworktime/releases/tag/v1.1.1)) or the workaround to enable flexi time.

**Comment by gsauthof** [comment]
I'm also affected by this issue. When I opened the app this morning everything was empty in the table on the main screen. Also when switching to the previous week. I restarted the app and only then the timezone migration screen appeared. I selected the Berlin time zone. But still all tables are empty. I checked in Google Play after that, and the app was auto-updated 2021-02-02.

I can confirm that when going to the details view (of a week) then all old entries are still there.

---

So I've just updated again via google play (a few minutes ago) and I can confirm that the latest update fixes this issue for me. That means the week views show all the entered data.

**Comment by mathisdt** [comment]
At 7 p.m. CET I got the confirmation from Google that v1.1.1 is approved for the Play Store, so hopefully the affected devices will update this night and the users will be happy again from tomorrow on.

Thanks to all involved people, especially to @dliw for providing a solution so speedily!
